# Generated by Django 5.2.1 on 2025-05-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_empleado', models.CharField(choices=[('Cocinero', 'Cocinero'), ('Domiciliario', 'Domiciliario'), ('Cajero', 'Cajero')], max_length=20)),
            ],
        ),
    ]
