# Generated by Django 5.2.1 on 2025-05-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
