# Generated by Django 5.2.1 on 2025-05-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_pedido_alergias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
