# Generated by Django 5.2.1 on 2025-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En cocina', 'En cocina'), ('En reparto', 'En reparto'), ('Entregado', 'Entregado')], default='En cocina', max_length=20),
        ),
    ]
