# Generated by Django 5.2.1 on 2025-05-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En cocina', 'En cocina'), ('En cocina1', 'En cocina1'), ('En reparto', 'En reparto'), ('Entregado', 'Entregado'), ('Enviado', 'Enviado'), ('En reparto', 'En reparto')], max_length=20),
        ),
    ]
