# Generated by Django 5.2.1 on 2025-05-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
